# Resolve react_native_pods.rb with node to allow for hoisting
$RNFirebaseAsStaticFramework = true
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DatingApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'GoogleUtilities',:modular_headers => true
  pod 'FirebaseCoreInternal',:modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  # pod 'RNFBApp', :modular_headers => true
  # pod 'RNFBAnalytics', :modular_headers => true
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'GoogleSignIn'
  permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
  # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  $RNFirebaseAnalyticsWithoutAdIdSupport=true
  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:hermes_enabled],
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'DatingAppTests' do
    # inherit! :complete
    inherit! :search_paths
    # Pods for testing
  end
  # use_native_modules!

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
